// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: protos/meta_transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QdbTransactionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Extension     string                 `protobuf:"bytes,4,opt,name=extension,proto3" json:"extension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QdbTransactionCmd) Reset() {
	*x = QdbTransactionCmd{}
	mi := &file_protos_meta_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QdbTransactionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QdbTransactionCmd) ProtoMessage() {}

func (x *QdbTransactionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QdbTransactionCmd.ProtoReflect.Descriptor instead.
func (*QdbTransactionCmd) Descriptor() ([]byte, []int) {
	return file_protos_meta_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *QdbTransactionCmd) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *QdbTransactionCmd) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QdbTransactionCmd) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *QdbTransactionCmd) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

type MetaTransaction struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TransactionId string                   `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	CmdList       []*QdbTransactionCmd     `protobuf:"bytes,2,rep,name=cmdList,proto3" json:"cmdList,omitempty"`
	MetaCmdList   []*MetaTransactionGossip `protobuf:"bytes,3,rep,name=metaCmdList,proto3" json:"metaCmdList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaTransaction) Reset() {
	*x = MetaTransaction{}
	mi := &file_protos_meta_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaTransaction) ProtoMessage() {}

func (x *MetaTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaTransaction.ProtoReflect.Descriptor instead.
func (*MetaTransaction) Descriptor() ([]byte, []int) {
	return file_protos_meta_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *MetaTransaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *MetaTransaction) GetCmdList() []*QdbTransactionCmd {
	if x != nil {
		return x.CmdList
	}
	return nil
}

func (x *MetaTransaction) GetMetaCmdList() []*MetaTransactionGossip {
	if x != nil {
		return x.MetaCmdList
	}
	return nil
}

type MetaTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *MetaTransaction       `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaTransactionRequest) Reset() {
	*x = MetaTransactionRequest{}
	mi := &file_protos_meta_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaTransactionRequest) ProtoMessage() {}

func (x *MetaTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaTransactionRequest.ProtoReflect.Descriptor instead.
func (*MetaTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protos_meta_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *MetaTransactionRequest) GetTransaction() *MetaTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type ExecNoTranRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	CmdList       []*QdbTransactionCmd     `protobuf:"bytes,1,rep,name=cmdList,proto3" json:"cmdList,omitempty"`
	MetaCmdList   []*MetaTransactionGossip `protobuf:"bytes,2,rep,name=metaCmdList,proto3" json:"metaCmdList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecNoTranRequest) Reset() {
	*x = ExecNoTranRequest{}
	mi := &file_protos_meta_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecNoTranRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecNoTranRequest) ProtoMessage() {}

func (x *ExecNoTranRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_meta_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecNoTranRequest.ProtoReflect.Descriptor instead.
func (*ExecNoTranRequest) Descriptor() ([]byte, []int) {
	return file_protos_meta_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ExecNoTranRequest) GetCmdList() []*QdbTransactionCmd {
	if x != nil {
		return x.CmdList
	}
	return nil
}

func (x *ExecNoTranRequest) GetMetaCmdList() []*MetaTransactionGossip {
	if x != nil {
		return x.MetaCmdList
	}
	return nil
}

var File_protos_meta_transaction_proto protoreflect.FileDescriptor

const file_protos_meta_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1dprotos/meta_transaction.proto\x12\x04spqr\x1a\x1bgoogle/protobuf/empty.proto\x1a%protos/meta_transaction_request.proto\"s\n" +
	"\x11QdbTransactionCmd\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1c\n" +
	"\textension\x18\x04 \x01(\tR\textension\"\xa9\x01\n" +
	"\x0fMetaTransaction\x12$\n" +
	"\rtransactionId\x18\x01 \x01(\tR\rtransactionId\x121\n" +
	"\acmdList\x18\x02 \x03(\v2\x17.spqr.QdbTransactionCmdR\acmdList\x12=\n" +
	"\vmetaCmdList\x18\x03 \x03(\v2\x1b.spqr.MetaTransactionGossipR\vmetaCmdList\"Q\n" +
	"\x16MetaTransactionRequest\x127\n" +
	"\vtransaction\x18\x01 \x01(\v2\x15.spqr.MetaTransactionR\vtransaction\"\x85\x01\n" +
	"\x11ExecNoTranRequest\x121\n" +
	"\acmdList\x18\x01 \x03(\v2\x17.spqr.QdbTransactionCmdR\acmdList\x12=\n" +
	"\vmetaCmdList\x18\x02 \x03(\v2\x1b.spqr.MetaTransactionGossipR\vmetaCmdList2\x9d\x01\n" +
	"\x16MetaTransactionService\x12?\n" +
	"\n" +
	"ExecNoTran\x12\x17.spqr.ExecNoTranRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\bExecTran\x12\x1c.spqr.MetaTransactionRequest\x1a\x16.google.protobuf.Empty\"\x00B\fZ\n" +
	"spqr/protob\x06proto3"

var (
	file_protos_meta_transaction_proto_rawDescOnce sync.Once
	file_protos_meta_transaction_proto_rawDescData []byte
)

func file_protos_meta_transaction_proto_rawDescGZIP() []byte {
	file_protos_meta_transaction_proto_rawDescOnce.Do(func() {
		file_protos_meta_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_meta_transaction_proto_rawDesc), len(file_protos_meta_transaction_proto_rawDesc)))
	})
	return file_protos_meta_transaction_proto_rawDescData
}

var file_protos_meta_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_meta_transaction_proto_goTypes = []any{
	(*QdbTransactionCmd)(nil),      // 0: spqr.QdbTransactionCmd
	(*MetaTransaction)(nil),        // 1: spqr.MetaTransaction
	(*MetaTransactionRequest)(nil), // 2: spqr.MetaTransactionRequest
	(*ExecNoTranRequest)(nil),      // 3: spqr.ExecNoTranRequest
	(*MetaTransactionGossip)(nil),  // 4: spqr.MetaTransactionGossip
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_protos_meta_transaction_proto_depIdxs = []int32{
	0, // 0: spqr.MetaTransaction.cmdList:type_name -> spqr.QdbTransactionCmd
	4, // 1: spqr.MetaTransaction.metaCmdList:type_name -> spqr.MetaTransactionGossip
	1, // 2: spqr.MetaTransactionRequest.transaction:type_name -> spqr.MetaTransaction
	0, // 3: spqr.ExecNoTranRequest.cmdList:type_name -> spqr.QdbTransactionCmd
	4, // 4: spqr.ExecNoTranRequest.metaCmdList:type_name -> spqr.MetaTransactionGossip
	3, // 5: spqr.MetaTransactionService.ExecNoTran:input_type -> spqr.ExecNoTranRequest
	2, // 6: spqr.MetaTransactionService.ExecTran:input_type -> spqr.MetaTransactionRequest
	5, // 7: spqr.MetaTransactionService.ExecNoTran:output_type -> google.protobuf.Empty
	5, // 8: spqr.MetaTransactionService.ExecTran:output_type -> google.protobuf.Empty
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_meta_transaction_proto_init() }
func file_protos_meta_transaction_proto_init() {
	if File_protos_meta_transaction_proto != nil {
		return
	}
	file_protos_meta_transaction_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_meta_transaction_proto_rawDesc), len(file_protos_meta_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_meta_transaction_proto_goTypes,
		DependencyIndexes: file_protos_meta_transaction_proto_depIdxs,
		MessageInfos:      file_protos_meta_transaction_proto_msgTypes,
	}.Build()
	File_protos_meta_transaction_proto = out.File
	file_protos_meta_transaction_proto_goTypes = nil
	file_protos_meta_transaction_proto_depIdxs = nil
}
