// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: protos/meta_transaction_request.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetaTransactionGossipService_ApplyMeta_FullMethodName = "/spqr.MetaTransactionGossipService/ApplyMeta"
)

// MetaTransactionGossipServiceClient is the client API for MetaTransactionGossipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaTransactionGossipServiceClient interface {
	ApplyMeta(ctx context.Context, in *MetaTransactionGossipRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type metaTransactionGossipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaTransactionGossipServiceClient(cc grpc.ClientConnInterface) MetaTransactionGossipServiceClient {
	return &metaTransactionGossipServiceClient{cc}
}

func (c *metaTransactionGossipServiceClient) ApplyMeta(ctx context.Context, in *MetaTransactionGossipRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MetaTransactionGossipService_ApplyMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaTransactionGossipServiceServer is the server API for MetaTransactionGossipService service.
// All implementations must embed UnimplementedMetaTransactionGossipServiceServer
// for forward compatibility.
type MetaTransactionGossipServiceServer interface {
	ApplyMeta(context.Context, *MetaTransactionGossipRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMetaTransactionGossipServiceServer()
}

// UnimplementedMetaTransactionGossipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaTransactionGossipServiceServer struct{}

func (UnimplementedMetaTransactionGossipServiceServer) ApplyMeta(context.Context, *MetaTransactionGossipRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyMeta not implemented")
}
func (UnimplementedMetaTransactionGossipServiceServer) mustEmbedUnimplementedMetaTransactionGossipServiceServer() {
}
func (UnimplementedMetaTransactionGossipServiceServer) testEmbeddedByValue() {}

// UnsafeMetaTransactionGossipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaTransactionGossipServiceServer will
// result in compilation errors.
type UnsafeMetaTransactionGossipServiceServer interface {
	mustEmbedUnimplementedMetaTransactionGossipServiceServer()
}

func RegisterMetaTransactionGossipServiceServer(s grpc.ServiceRegistrar, srv MetaTransactionGossipServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetaTransactionGossipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaTransactionGossipService_ServiceDesc, srv)
}

func _MetaTransactionGossipService_ApplyMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaTransactionGossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaTransactionGossipServiceServer).ApplyMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaTransactionGossipService_ApplyMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaTransactionGossipServiceServer).ApplyMeta(ctx, req.(*MetaTransactionGossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaTransactionGossipService_ServiceDesc is the grpc.ServiceDesc for MetaTransactionGossipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaTransactionGossipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spqr.MetaTransactionGossipService",
	HandlerType: (*MetaTransactionGossipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyMeta",
			Handler:    _MetaTransactionGossipService_ApplyMeta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/meta_transaction_request.proto",
}
